version: '3'
services:
  profit-loss:
    image: haynesx11/bybit-profit-loss:${TAG}
    container_name: bybit-profit-loss
    command: >
      sh -c "
      python main.py"
    ports:
      - 8001:8001
    expose:
      - 8001
    env_file:
      - ../env/bybit-profit-loss.env
    volumes:
      - ../bybit-profit-loss-data:/home/bybit-profit-loss


